"use strict";

const PDFDocument = require("pdfkit");
const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle,
        Table, TableRow, TableCell, WidthType, VerticalAlign } = require("docx");

// ─── Helpers ──────────────────────────────────────────────────────────────────

function formatDate(d = new Date()) {
  return d.toISOString().slice(0, 10); // YYYY-MM-DD
}

function formatDateLong(d = new Date()) {
  try {
    return d.toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  } catch {
    return formatDate(d);
  }
}

function getFilename(pdfName, format) {
  const base = (pdfName || "Quiz")
    .replace(/\.pdf$/i, "")
    .replace(/[^a-zA-Z0-9_\-]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "")
    .slice(0, 60);
  const ext = format === "docx" ? "docx" : "pdf";
  return `Quiz_${base}_${formatDate()}.${ext}`;
}

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function prepareQuestions(questions, settings) {
  let qs = questions.map((q) => ({ ...q }));
  if (settings.shuffleQuestions) qs = shuffle(qs);
  if (settings.shuffleOptions) {
    qs = qs.map((q) => {
      if (q.type !== "mcq" || !Array.isArray(q.options)) return q;
      const correct = q.options[q.answerIndex];
      const newOpts = shuffle(q.options);
      return { ...q, options: newOpts, answerIndex: newOpts.indexOf(correct) };
    });
  }
  return qs;
}

function getAnswerLabel(q) {
  if (q.type === "mcq") return `${String.fromCharCode(65 + q.answerIndex)}) ${q.options[q.answerIndex]}`;
  if (q.type === "true_false") return q.answer ? "True" : "False";
  return q.answer || "";
}

// Short form used in answer key table column (avoids wrapping)
function getAnswerShort(q) {
  if (q.type === "mcq") return String.fromCharCode(65 + q.answerIndex);
  if (q.type === "true_false") return q.answer ? "True" : "False";
  const ans = String(q.answer || "");
  return ans.length > 22 ? ans.slice(0, 20) + "..." : ans;
}

function capitalize(s) {
  if (!s) return "";
  return s.charAt(0).toUpperCase() + s.slice(1).replace(/_/g, " ");
}

// ─── Type / section metadata ──────────────────────────────────────────────────

const TYPE_ORDER = ["mcq", "true_false", "fill_blank", "short_answer"];
const SECTION_LETTERS = ["A", "B", "C", "D"];

const TYPE_LABEL = {
  mcq:          "Multiple Choice Questions",
  true_false:   "True / False",
  fill_blank:   "Fill in the Blanks",
  short_answer: "Short Answer Questions",
};

const TYPE_SHORT = {
  mcq:          "MCQ",
  true_false:   "True / False",
  fill_blank:   "Fill in the Blank",
  short_answer: "Short Answer",
};

// ─── PDF design tokens ────────────────────────────────────────────────────────

const C = {
  brand:     "#4f46e5",
  brandDark: "#3730a3",
  dark:      "#1e293b",
  mid:       "#475569",
  light:     "#94a3b8",
  vlight:    "#cbd5e1",
  divider:   "#e2e8f0",
  bg:        "#f8fafc",
  white:     "#ffffff",
  // Difficulty colours
  easy:      "#10b981",  easyBg:   "#ecfdf5",
  medium:    "#f59e0b",  mediumBg: "#fffbeb",
  hard:      "#ef4444",  hardBg:   "#fff1f2",
};

// A4 = 595 x 842 pt
const PW = 595;
const PH = 842;
const M  = 52;          // side margin
const CW = PW - 2 * M;  // content width = 491 pt
// Content page: pdfkit margin=52, so content starts at y=52 and auto-pages before y≈790.
// Header drawn 0..26 in post-processing; footer drawn 812..842. Both outside the 52..790 zone.

// ─── Per-page header / footer (applied in post-processing via bufferPages) ────

function _drawHeader(doc, quizTitle, pageNum) {
  // Thin accent bar
  doc.rect(0, 0, PW, 4).fill(C.brand);

  // QUIZELO wordmark (left)
  doc.font("Helvetica-Bold").fontSize(7).fillColor(C.brand)
    .text("QUIZELO", M, 10, { lineBreak: false, width: 56 });

  // Quiz title (centre)
  const t = quizTitle.length > 52 ? quizTitle.slice(0, 49) + "..." : quizTitle;
  doc.font("Helvetica").fontSize(7).fillColor(C.light)
    .text(t, M + 60, 10, { lineBreak: false, width: CW - 110 });

  // Page number (right)
  doc.font("Helvetica").fontSize(7).fillColor(C.vlight)
    .text(`Page ${pageNum}`, M, 10, { align: "right", width: CW, lineBreak: false });

  // Underline
  doc.moveTo(M, 22).lineTo(PW - M, 22)
    .strokeColor(C.divider).lineWidth(0.5).stroke();
}

function _drawFooter(doc, pageNum, totalPages, dateStr) {
  const fy = PH - 28;
  doc.moveTo(M, fy).lineTo(PW - M, fy)
    .strokeColor(C.divider).lineWidth(0.5).stroke();
  doc.font("Helvetica").fontSize(7).fillColor(C.vlight)
    .text(`Generated by Quizelo  |  ${dateStr}`, M, fy + 7, { lineBreak: false })
    .text(`Page ${pageNum} of ${totalPages}`, M, fy + 7, { align: "right", width: CW, lineBreak: false });
}

// ─── PDF Builder ──────────────────────────────────────────────────────────────

async function buildPDF(questions, settings, pdfName) {
  return new Promise((resolve, reject) => {
    try {
      const qs = prepareQuestions(questions, settings);

      // ── Derived metadata ────────────────────────────────────────────────────
      const presentTypes = TYPE_ORDER.filter(t => qs.some(q => q.type === t));
      const uniqueDiffs  = [...new Set(qs.map(q => q.difficulty || "medium"))];
      const overallDiff  = uniqueDiffs.length === 1 ? capitalize(uniqueDiffs[0]) : "Mixed";
      const typeLabels   = presentTypes.map(t => TYPE_SHORT[t]).join(", ");
      const totalMarks   = qs.length;
      const estTime      = Math.max(10, qs.length * 2);
      const shortTitle   = (pdfName || "Quiz").replace(/\.pdf$/i, "").replace(/_/g, " ").slice(0, 55);
      const dateLong     = formatDateLong();
      const dateShort    = formatDate();

      // ── Section grouping (by type, preserving shuffle order within each type)
      let globalNum = 0;
      const sections = presentTypes.map((type, idx) => ({
        letter:    SECTION_LETTERS[idx],
        type,
        label:     TYPE_LABEL[type],
        questions: qs.filter(q => q.type === type).map(q => ({ ...q, _num: ++globalNum })),
      }));

      // Flat ordered list (by global number) used in the answer key
      const orderedQs = sections.flatMap(s => s.questions);

      // ── PDFDocument ─────────────────────────────────────────────────────────
      const doc = new PDFDocument({
        margin: M,
        size: "A4",
        autoFirstPage: true,
        bufferPages: true,          // enables switchToPage for header/footer post-processing
        info: {
          Title:   `Quiz: ${shortTitle}`,
          Author:  "Quizelo",
          Creator: "Quizelo AI Quiz Generator",
          CreationDate: new Date(),
        },
      });

      const buffers = [];
      doc.on("data",  chunk => buffers.push(chunk));
      doc.on("end",   ()    => resolve(Buffer.concat(buffers)));
      doc.on("error", reject);

      // ══════════════════════════════════════════════════════════════════════
      // COVER PAGE
      // ══════════════════════════════════════════════════════════════════════

      // Top accent bars
      doc.rect(0, 0, PW, 14).fill(C.brand);
      doc.rect(0, 14, PW, 5).fill(C.brandDark);

      // Wordmark
      doc.font("Helvetica-Bold").fontSize(36).fillColor(C.brand)
        .text("QUIZELO", M, 46);
      doc.font("Helvetica").fontSize(12).fillColor(C.light)
        .text("AI-Powered Quiz Generator", M, 90);

      // Divider pair
      doc.moveTo(M, 116).lineTo(PW - M, 116).strokeColor(C.brand).lineWidth(2.5).stroke();
      doc.moveTo(M, 121).lineTo(PW - M, 121).strokeColor(C.divider).lineWidth(0.5).stroke();

      // Metadata card
      const cardX = M;
      const cardY = 138;
      const cardW = CW;
      const cardH = 388;

      // Drop-shadow (offset gray rect)
      doc.rect(cardX + 3, cardY + 3, cardW, cardH).fill("#dde1ea");
      // Card surface
      doc.roundedRect(cardX, cardY, cardW, cardH, 7).fillAndStroke(C.white, C.divider);

      // Vertical divider between label column and value column
      doc.moveTo(cardX + 165, cardY + 20).lineTo(cardX + 165, cardY + cardH - 20)
        .strokeColor(C.divider).lineWidth(0.5).stroke();

      const metaRows = [
        ["Quiz Title",       shortTitle,                         true ],
        ["Source",           pdfName || "N/A",                   false],
        ["Generated On",     dateLong,                           false],
        ["Difficulty",       overallDiff,                        false],
        ["Question Types",   typeLabels,                         false],
        ["Total Questions",  String(qs.length),                  false],
        ["Estimated Time",   `${estTime} Minutes`,               false],
        ["Total Marks",      String(totalMarks),                 false],
      ];

      let rowY = cardY + 26;
      metaRows.forEach(([label, value, isBig], ri) => {
        // Label
        doc.font("Helvetica-Bold").fontSize(7.5).fillColor(C.light)
          .text(label.toUpperCase(), cardX + 16, rowY, { width: 138, lineBreak: false });

        // Value
        doc.font("Helvetica-Bold").fontSize(isBig ? 13.5 : 11.5).fillColor(C.dark)
          .text(value, cardX + 177, rowY - (isBig ? 2 : 0), {
            width: cardW - 193, lineBreak: false, ellipsis: true,
          });

        rowY += 44;

        // Row separator (skip last)
        if (ri < metaRows.length - 1) {
          doc.moveTo(cardX + 16, rowY - 12)
            .lineTo(cardX + cardW - 16, rowY - 12)
            .strokeColor(C.divider).lineWidth(0.3).stroke();
        }
      });

      // Cover footer strip
      doc.rect(0, PH - 44, PW, 44).fill(C.bg);
      doc.font("Helvetica").fontSize(8.5).fillColor(C.light)
        .text("Quizelo  |  AI-Powered Quiz Generator", M, PH - 26,
              { align: "center", width: CW, lineBreak: false });

      // ══════════════════════════════════════════════════════════════════════
      // QUESTION PAGES
      // pdfkit auto-margin = M = 52 pt.
      // Header post-processing writes at y=0..22 (safe, no overlap with content).
      // Footer post-processing writes at y=814..842 (safe, content stops at ~790).
      // ══════════════════════════════════════════════════════════════════════

      doc.addPage();
      // doc.y is now 52 (the margin). Content flows freely from here.

      // Available vertical space per content page before auto-page:
      // pdfkit auto-pages when doc.y > PH - M = 790. We add our own guard at 750.
      const PAGE_GUARD = 750;

      function needsPage(estimatedPts) {
        return doc.y + estimatedPts > PAGE_GUARD;
      }

      // Only add a page when there is already meaningful content on the current
      // page (doc.y is well past the top margin).  If pdfkit just auto-added a
      // page for us, doc.y == M (52) and a second addPage() would produce a
      // blank page — so we skip it in that case.
      function safeAddPage() {
        if (doc.y > M + 8) {
          doc.addPage();
        }
        // else: already at the top of a fresh page — reuse it
      }

      for (const section of sections) {
        // ── Section header bar ───────────────────────────────────────────────
        if (needsPage(90)) doc.addPage();

        const secBarY = doc.y;

        // Background bar + left accent stripe
        doc.rect(M, secBarY, CW, 28).fill(C.bg);
        doc.rect(M, secBarY, 5, 28).fill(C.brand);

        // "Section A" label
        doc.font("Helvetica-Bold").fontSize(9.5).fillColor(C.brand)
          .text(`Section ${section.letter}`, M + 13, secBarY + 8, { lineBreak: false });

        // " ·  Label"
        doc.font("Helvetica-Bold").fontSize(9.5).fillColor(C.dark)
          .text(`   ·   ${section.label}`, M + 13 + 56, secBarY + 8, { lineBreak: false });

        // Question range (right side)
        const nums = section.questions.map(q => q._num);
        const rangeStr = nums.length === 1
          ? `Q${nums[0]}`
          : `Q${nums[0]} - Q${nums[nums.length - 1]}`;
        doc.font("Helvetica").fontSize(8).fillColor(C.light)
          .text(rangeStr, M, secBarY + 10, { align: "right", width: CW, lineBreak: false });

        doc.y = secBarY + 38;

        // ── Questions in this section ─────────────────────────────────────────
        for (const q of section.questions) {
          // Rough height estimate (generously conservative)
          const qLines    = Math.ceil(q.question.length / 60);
          const qTextH    = Math.max(1, qLines) * 17;
          const optH      = q.type === "mcq"
            ? (q.options?.length || 4) * 22
            : q.type === "true_false" ? 26
            : 80; // fill_blank / short_answer (3 lines)
          const extraH    = (settings.includeAnswers && q.type !== "mcq" ? 20 : 0)
                          + (settings.includeAnswers && settings.includeExplanations && q.explanation ? 24 : 0)
                          + (q.source ? 22 : 0);
          const totalEst  = 38 + qTextH + optH + extraH + 30;

          if (needsPage(totalEst)) doc.addPage();

          const qTop = doc.y;

          // ── Badges row: [Q N (1 Mark)] [Difficulty] [Type] ───────────────
          // Number pill
          const pillW = 80;
          doc.roundedRect(M, qTop, pillW, 19, 3).fill(C.brand);
          doc.font("Helvetica-Bold").fontSize(8.5).fillColor(C.white)
            .text(`Q ${q._num}   (1 Mark)`, M + 6, qTop + 4, { lineBreak: false });

          // Difficulty badge
          const diffCol  = C[q.difficulty]   || C.medium;
          const diffBg   = C[`${q.difficulty}Bg`] || C.mediumBg;
          doc.roundedRect(M + pillW + 7, qTop, 54, 19, 3).fillAndStroke(diffBg, diffCol);
          doc.font("Helvetica-Bold").fontSize(8).fillColor(diffCol)
            .text(capitalize(q.difficulty || "medium"), M + pillW + 13, qTop + 5, { lineBreak: false });

          // Type badge
          const typeStr = TYPE_SHORT[q.type] || q.type;
          const typeBx  = M + pillW + 7 + 54 + 6;
          const typeBw  = Math.max(doc.font("Helvetica").fontSize(7.5).widthOfString(typeStr) + 16, 50);
          doc.roundedRect(typeBx, qTop, typeBw, 19, 3).fillAndStroke(C.bg, C.divider);
          doc.font("Helvetica").fontSize(7.5).fillColor(C.light)
            .text(typeStr, typeBx + 8, qTop + 5.5, { lineBreak: false });

          doc.y = qTop + 27;

          // ── Question text ────────────────────────────────────────────────
          doc.font("Helvetica-Bold").fontSize(12.5).fillColor(C.dark)
            .text(q.question, M, doc.y, { width: CW, lineBreak: true });
          doc.y += 10;

          // ── Options ──────────────────────────────────────────────────────
          if (q.type === "mcq" && Array.isArray(q.options)) {
            for (let oi = 0; oi < q.options.length; oi++) {
              const letter    = String.fromCharCode(65 + oi);
              const isCorrect = settings.includeAnswers && oi === q.answerIndex;
              const optY      = doc.y;

              // Checkbox square (drawn as a 10x10 rectangle)
              if (isCorrect) {
                doc.rect(M + 6, optY + 3, 10, 10).fill(C.brand);
                // "v" inside as a rough checkmark (Helvetica has no tick glyph)
                doc.font("Helvetica-Bold").fontSize(8).fillColor(C.white)
                  .text("v", M + 8.5, optY + 4, { lineBreak: false });
              } else {
                doc.rect(M + 6, optY + 3, 10, 10)
                  .strokeColor(C.vlight).lineWidth(1).stroke();
              }

              doc.font(isCorrect ? "Helvetica-Bold" : "Helvetica")
                .fontSize(11.5).fillColor(isCorrect ? C.brand : C.mid)
                .text(`${letter}.   ${q.options[oi]}`, M + 25, optY,
                      { width: CW - 29, lineBreak: true });
              doc.y += 4;
            }
          }

          if (q.type === "true_false") {
            const tfY = doc.y;
            doc.rect(M + 6, tfY + 3, 10, 10).strokeColor(C.vlight).lineWidth(1).stroke();
            doc.font("Helvetica").fontSize(11.5).fillColor(C.mid)
              .text("True", M + 23, tfY, { lineBreak: false });
            doc.rect(M + 88, tfY + 3, 10, 10).strokeColor(C.vlight).lineWidth(1).stroke();
            doc.font("Helvetica").fontSize(11.5).fillColor(C.mid)
              .text("False", M + 105, tfY, { lineBreak: false });
            doc.y = tfY + 22;
            doc.y += 4;

            if (settings.includeAnswers) {
              doc.font("Helvetica-Bold").fontSize(10.5).fillColor(C.brand)
                .text(`Answer:  ${q.answer ? "True" : "False"}`, M + 6, doc.y);
              doc.y += 6;
            }
          }

          if (q.type === "fill_blank" || q.type === "short_answer") {
            doc.y += 6;
            doc.font("Helvetica").fontSize(9).fillColor(C.mid)
              .text("Answer:", M + 6, doc.y);
            doc.y += 4;

            const lineCount = q.type === "short_answer" ? 3 : 1;
            for (let li = 0; li < lineCount; li++) {
              const lineY = doc.y + 13;
              doc.moveTo(M + 6, lineY).lineTo(PW - M - 10, lineY)
                .strokeColor(C.vlight).lineWidth(0.8).stroke();
              doc.y = lineY + 16;
            }

            if (settings.includeAnswers && q.answer) {
              doc.y += 4;
              doc.font("Helvetica-Bold").fontSize(10.5).fillColor(C.brand)
                .text(`Answer:  ${q.answer}`, M + 6, doc.y, { width: CW - 10, lineBreak: true });
              doc.y += 4;
            }
          }

          // ── Source citation (text-only, no emoji) ────────────────────────
          if (q.source) {
            const src   = q.source;
            const topic = (src.topic || src.section || "").slice(0, 55);
            const loc   = [
              `Page ${src.page}`,
              (src.startLine && src.endLine) ? `Lines ${src.startLine}-${src.endLine}` : null,
            ].filter(Boolean).join("   ");

            doc.y += 5;
            doc.font("Helvetica-Bold").fontSize(7.5).fillColor(C.light)
              .text("Source:", M + 4, doc.y, { lineBreak: false });
            doc.font("Helvetica").fontSize(7.5).fillColor(C.light)
              .text(`   ${topic}   |   ${loc}`, M + 4, doc.y, { width: CW - 8, lineBreak: true });
          }

          // ── Inline explanation ────────────────────────────────────────────
          if (settings.includeAnswers && settings.includeExplanations && q.explanation) {
            doc.y += 3;
            doc.font("Helvetica-Oblique").fontSize(9).fillColor(C.light)
              .text(`Explanation:  ${q.explanation}`, M + 4, doc.y,
                    { width: CW - 8, lineBreak: true });
          }

          // ── Separator ────────────────────────────────────────────────────
          doc.y += 9;
          doc.moveTo(M, doc.y).lineTo(PW - M, doc.y)
            .strokeColor(C.divider).lineWidth(0.5).stroke();
          doc.y += 15;
        }

        doc.y += 6; // breathing room between sections
      }

      // ══════════════════════════════════════════════════════════════════════
      // ANSWER KEY  (table layout)
      // ══════════════════════════════════════════════════════════════════════
      if (settings.includeAnswers) {
        safeAddPage();

        // Title
        doc.font("Helvetica-Bold").fontSize(19).fillColor(C.brand)
          .text("Answer Key", M, doc.y);
        doc.y += 28;
        doc.font("Helvetica").fontSize(9.5).fillColor(C.light)
          .text(`${qs.length} Questions   |   ${totalMarks} Total Marks`, M, doc.y);
        doc.y += 26;

        // Table columns: Q.No | Correct Answer | Topic | Page
        // Widths must sum to CW = 491
        const cols = [
          { label: "Q.No",           w: 40  },
          { label: "Correct Answer", w: 190 },
          { label: "Topic",          w: 175 },
          { label: "Page",           w: 86  },
        ];
        const ROW_H = 22;

        function drawTableRow(y, cells, bg, bold, textColors) {
          // Row background
          if (bg) doc.rect(M, y, CW, ROW_H).fill(bg);

          // Borders
          doc.moveTo(M, y).lineTo(PW - M, y).strokeColor(C.divider).lineWidth(0.4).stroke();
          doc.moveTo(M, y + ROW_H).lineTo(PW - M, y + ROW_H).strokeColor(C.divider).lineWidth(0.4).stroke();

          // Cell text
          let cx = M;
          cells.forEach((text, ci) => {
            doc.font(bold[ci] ? "Helvetica-Bold" : "Helvetica")
              .fontSize(9).fillColor(textColors[ci])
              .text(text, cx + 6, y + 7, {
                width: cols[ci].w - 10,
                lineBreak: false,
                ellipsis: true,
              });
            cx += cols[ci].w;
          });
        }

        // Header row
        drawTableRow(
          doc.y,
          cols.map(c => c.label),
          C.bg,
          [true, true, true, true],
          [C.mid, C.mid, C.mid, C.mid],
        );
        doc.y += ROW_H;

        // Data rows
        for (let i = 0; i < orderedQs.length; i++) {
          const q = orderedQs[i];

          // Estimate row height including optional explanation
          const expH = settings.includeExplanations && q.explanation
            ? Math.max(1, Math.ceil(q.explanation.length / 80)) * 14 + 8
            : 0;

          if (doc.y + ROW_H + expH > PAGE_GUARD) safeAddPage();

          const rowY = doc.y;
          const rowBg = i % 2 === 0 ? "#fafafa" : C.white;

          drawTableRow(
            rowY,
            [
              String(i + 1),
              getAnswerShort(q),
              (q.source?.topic || q.source?.section || "-").slice(0, 32),
              q.source?.page ? String(q.source.page) : "-",
            ],
            rowBg,
            [true,  true,  false, false],
            [C.dark, C.brand, C.mid, C.mid],
          );

          doc.y = rowY + ROW_H;

          // Optional full answer + explanation below the row
          if (settings.includeExplanations && q.explanation) {
            doc.font("Helvetica-Oblique").fontSize(8.5).fillColor(C.light)
              .text(`   ${q.explanation}`, M + 42, doc.y, {
                width: CW - 46,
                lineBreak: true,
              });
            doc.y += 4;
          }
        }
      }

      // ══════════════════════════════════════════════════════════════════════
      // POST-PROCESS: add header + footer to every non-cover page
      // ══════════════════════════════════════════════════════════════════════
      const range = doc.bufferedPageRange();
      const contentPageCount = range.count - 1; // page 0 = cover

      for (let pi = 1; pi < range.count; pi++) {
        const contentPageNum = pi; // 1-based
        doc.switchToPage(pi);
        _drawHeader(doc, shortTitle, contentPageNum);
        _drawFooter(doc, contentPageNum, contentPageCount, dateShort);
      }

      doc.flushPages();
      doc.end();

    } catch (err) {
      reject(err);
    }
  });
}

// ─── DOCX Builder ─────────────────────────────────────────────────────────────

async function buildDOCX(questions, settings, pdfName) {
  const qs = prepareQuestions(questions, settings);
  const shortTitle = (pdfName || "Quiz").replace(/\.pdf$/i, "").replace(/_/g, " ");
  const dateLong   = formatDateLong();

  // Section grouping (same as PDF)
  const presentTypes = TYPE_ORDER.filter(t => qs.some(q => q.type === t));
  let globalNum = 0;
  const sections = presentTypes.map((type, idx) => ({
    letter:    SECTION_LETTERS[idx],
    type,
    label:     TYPE_LABEL[type],
    questions: qs.filter(q => q.type === type).map(q => ({ ...q, _num: ++globalNum })),
  }));
  const orderedQs = sections.flatMap(s => s.questions);

  const children = [];

  // ── Cover header ────────────────────────────────────────────────────────────
  children.push(new Paragraph({
    children: [new TextRun({ text: "QUIZELO", bold: true, size: 56, color: "4f46e5" })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 80 },
  }));
  children.push(new Paragraph({
    children: [new TextRun({ text: "AI-Powered Quiz Generator", size: 22, color: "94a3b8" })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 400 },
  }));

  children.push(new Paragraph({
    text: `Quiz: ${shortTitle}`,
    heading: HeadingLevel.HEADING_1,
    spacing: { after: 100 },
  }));

  [
    [`Generated: ${dateLong}`, "888888"],
    [`Questions:  ${qs.length}     |     Total Marks: ${qs.length}     |     Est. Time: ${Math.max(10, qs.length * 2)} min`, "888888"],
  ].forEach(([text, color]) => {
    children.push(new Paragraph({
      children: [new TextRun({ text, color, size: 20 })],
      spacing: { after: 80 },
    }));
  });

  children.push(new Paragraph({ border: { bottom: { color: "4f46e5", space: 1, value: BorderStyle.SINGLE, size: 12 } }, spacing: { after: 400 } }));

  // ── Sections ────────────────────────────────────────────────────────────────
  for (const section of sections) {
    // Section heading
    children.push(new Paragraph({
      children: [
        new TextRun({ text: `Section ${section.letter}  `, bold: true, size: 26, color: "4f46e5" }),
        new TextRun({ text: section.label, bold: true, size: 24, color: "1e293b" }),
      ],
      spacing: { before: 400, after: 200 },
    }));

    for (const q of section.questions) {
      // Question number + text
      children.push(new Paragraph({
        children: [
          new TextRun({ text: `Q${q._num}.  `, bold: true, size: 24 }),
          new TextRun({ text: `(1 Mark)  `, size: 18, color: "94a3b8" }),
          new TextRun({ text: capitalize(q.difficulty || "medium"), size: 18, color: "f59e0b", italics: true }),
        ],
        spacing: { before: 240, after: 60 },
      }));

      children.push(new Paragraph({
        children: [new TextRun({ text: q.question, bold: true, size: 24 })],
        spacing: { after: 120 },
      }));

      // MCQ options
      if (q.type === "mcq" && Array.isArray(q.options)) {
        for (let oi = 0; oi < q.options.length; oi++) {
          const letter    = String.fromCharCode(65 + oi);
          const isCorrect = settings.includeAnswers && oi === q.answerIndex;
          children.push(new Paragraph({
            children: [
              new TextRun({ text: `[ ]   ${letter}.   ${q.options[oi]}`, bold: isCorrect, color: isCorrect ? "4f46e5" : "475569", size: 22 }),
            ],
            spacing: { after: 60 },
            indent: { left: 360 },
          }));
        }
      }

      // True / False
      if (q.type === "true_false") {
        children.push(new Paragraph({
          children: [new TextRun({ text: "[ ]  True                 [ ]  False", color: "475569", size: 22 })],
          spacing: { after: 80 },
          indent: { left: 360 },
        }));
        if (settings.includeAnswers) {
          children.push(new Paragraph({
            children: [new TextRun({ text: `Answer: ${q.answer ? "True" : "False"}`, bold: true, color: "4f46e5", size: 22 })],
            spacing: { after: 60 },
            indent: { left: 360 },
          }));
        }
      }

      // Fill blank / Short answer
      if (q.type === "fill_blank" || q.type === "short_answer") {
        const lineCount = q.type === "short_answer" ? 3 : 1;
        children.push(new Paragraph({
          children: [new TextRun({ text: "Answer:", size: 20, color: "475569" })],
          spacing: { after: 60 },
          indent: { left: 360 },
        }));
        for (let li = 0; li < lineCount; li++) {
          children.push(new Paragraph({
            children: [new TextRun({ text: "_".repeat(70), color: "cbd5e1", size: 20 })],
            spacing: { after: 80 },
            indent: { left: 360 },
          }));
        }
        if (settings.includeAnswers && q.answer) {
          children.push(new Paragraph({
            children: [new TextRun({ text: `Answer:  ${q.answer}`, bold: true, color: "4f46e5", size: 22 })],
            spacing: { after: 60 },
            indent: { left: 360 },
          }));
        }
      }

      // Source
      if (q.source) {
        const src = q.source;
        const topic = (src.topic || src.section || "").slice(0, 55);
        const loc   = [`Page ${src.page}`, src.startLine && src.endLine ? `Lines ${src.startLine}-${src.endLine}` : null].filter(Boolean).join("  |  ");
        children.push(new Paragraph({
          children: [new TextRun({ text: `Source:  ${topic}   |   ${loc}`, color: "94a3b8", size: 18, italics: true })],
          spacing: { after: 60 },
          indent: { left: 360 },
        }));
      }

      // Explanation
      if (settings.includeAnswers && settings.includeExplanations && q.explanation) {
        children.push(new Paragraph({
          children: [new TextRun({ text: `Explanation:  ${q.explanation}`, color: "94a3b8", size: 18, italics: true })],
          spacing: { after: 60 },
          indent: { left: 360 },
        }));
      }

      // Divider
      children.push(new Paragraph({
        border: { bottom: { color: "e2e8f0", space: 1, value: BorderStyle.SINGLE, size: 6 } },
        spacing: { after: 160 },
      }));
    }
  }

  // ── Answer Key (table) ────────────────────────────────────────────────────
  if (settings.includeAnswers) {
    children.push(new Paragraph({
      text: "Answer Key",
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      spacing: { before: 200, after: 300 },
    }));

    const makeCell = (text, bold, color) => new TableCell({
      children: [new Paragraph({
        children: [new TextRun({ text, bold: bold || false, color: color || "000000", size: 20 })],
      })],
      verticalAlign: VerticalAlign.CENTER,
      margins: { top: 60, bottom: 60, left: 100, right: 100 },
    });

    const tableRows = [
      // Header
      new TableRow({
        tableHeader: true,
        children: [
          makeCell("Q.No",           true, "475569"),
          makeCell("Correct Answer", true, "475569"),
          makeCell("Topic",          true, "475569"),
          makeCell("Page",           true, "475569"),
        ],
      }),
      // Data rows
      ...orderedQs.map((q, i) => new TableRow({
        children: [
          makeCell(String(i + 1),                                               true,  "1e293b"),
          makeCell(getAnswerShort(q),                                           true,  "4f46e5"),
          makeCell((q.source?.topic || q.source?.section || "-").slice(0, 35), false, "475569"),
          makeCell(q.source?.page ? String(q.source.page) : "-",               false, "475569"),
        ],
      })),
    ];

    children.push(new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      columnWidths: [1000, 3200, 3000, 1300], // DXA units (~= 1/20 pt), sum ~= 8500
      rows: tableRows,
    }));

    // Explanations block (below table if enabled)
    if (settings.includeExplanations) {
      children.push(new Paragraph({ text: "", spacing: { after: 300 } }));
      children.push(new Paragraph({
        text: "Explanations",
        heading: HeadingLevel.HEADING_2,
        spacing: { after: 200 },
      }));
      orderedQs.forEach((q, i) => {
        if (!q.explanation) return;
        children.push(new Paragraph({
          children: [
            new TextRun({ text: `${i + 1}. `, bold: true, size: 22 }),
            new TextRun({ text: q.explanation, size: 20, color: "475569" }),
          ],
          spacing: { after: 100 },
        }));
      });
    }
  }

  const doc = new Document({
    creator: "Quizelo",
    title:   `Quiz: ${shortTitle}`,
    sections: [{ properties: {}, children }],
  });

  return Packer.toBuffer(doc);
}

// ─── Public API ───────────────────────────────────────────────────────────────

module.exports = { buildPDF, buildDOCX, buildNotesPDF, buildNotesDOCX, getFilename };

// ─── Notes PDF Builder ────────────────────────────────────────────────────────

async function buildNotesPDF(notes) {
  return new Promise((resolve, reject) => {
    try {
      const title     = notes.title   || "Study Notes";
      const subject   = notes.subject || "";
      const sections  = Array.isArray(notes.sections) ? notes.sections : [];
      const quickRevision = Array.isArray(notes.quickRevision) ? notes.quickRevision : [];
      const dateLong  = formatDateLong();
      const dateShort = formatDate();

      const doc = new PDFDocument({
        margin: M, size: "A4", autoFirstPage: true, bufferPages: true,
        info: { Title: title, Author: "Quizelo", Creator: "Quizelo AI Notes Generator" },
      });

      const buffers = [];
      doc.on("data",  c => buffers.push(c));
      doc.on("end",   () => resolve(Buffer.concat(buffers)));
      doc.on("error", reject);

      const PAGE_GUARD = 750;
      function safeAddPage() { if (doc.y > M + 8) doc.addPage(); }
      function needsPage(h)  { return doc.y + h > PAGE_GUARD; }

      // ── Cover ─────────────────────────────────────────────────────────────
      doc.rect(0, 0, PW, 14).fill(C.brand);
      doc.rect(0, 14, PW, 5).fill(C.brandDark);

      doc.font("Helvetica-Bold").fontSize(36).fillColor(C.brand).text("QUIZELO", M, 46);
      doc.font("Helvetica").fontSize(12).fillColor(C.light).text("AI Study Notes Generator", M, 90);

      doc.moveTo(M, 116).lineTo(PW - M, 116).strokeColor(C.brand).lineWidth(2.5).stroke();
      doc.moveTo(M, 121).lineTo(PW - M, 121).strokeColor(C.divider).lineWidth(0.5).stroke();

      // Card
      const cX = M, cY = 138, cW = CW, cH = 228;
      doc.rect(cX + 3, cY + 3, cW, cH).fill("#dde1ea");
      doc.roundedRect(cX, cY, cW, cH, 7).fillAndStroke(C.white, C.divider);
      doc.moveTo(cX + 165, cY + 20).lineTo(cX + 165, cY + cH - 20).strokeColor(C.divider).lineWidth(0.5).stroke();

      const coverRows = [
        ["Document Title", title.slice(0, 55), true],
        ["Subject",        subject || "General", false],
        ["Generated On",   dateLong, false],
        ["Sections",       String(sections.length), false],
      ];
      let rY = cY + 26;
      coverRows.forEach(([label, value, big], ri) => {
        doc.font("Helvetica-Bold").fontSize(7.5).fillColor(C.light).text(label.toUpperCase(), cX + 16, rY, { width: 138, lineBreak: false });
        doc.font("Helvetica-Bold").fontSize(big ? 13.5 : 11.5).fillColor(C.dark).text(value, cX + 177, rY - (big ? 2 : 0), { width: cW - 193, lineBreak: false, ellipsis: true });
        rY += 44;
        if (ri < coverRows.length - 1) {
          doc.moveTo(cX + 16, rY - 12).lineTo(cX + cW - 16, rY - 12).strokeColor(C.divider).lineWidth(0.3).stroke();
        }
      });

      doc.rect(0, PH - 44, PW, 44).fill(C.bg);
      doc.font("Helvetica").fontSize(8.5).fillColor(C.light).text("Quizelo  |  AI-Powered Study Notes", M, PH - 26, { align: "center", width: CW, lineBreak: false });

      // ── Content pages ─────────────────────────────────────────────────────
      doc.addPage();

      sections.forEach((sec, si) => {
        if (needsPage(80)) safeAddPage();

        // Section header
        const shY = doc.y;
        doc.rect(M, shY, CW, 30).fill(C.bg);
        doc.rect(M, shY, 5, 30).fill(C.brand);
        doc.font("Helvetica-Bold").fontSize(13).fillColor(C.dark).text(sec.chapter || `Section ${si + 1}`, M + 14, shY + 8, { width: CW - 20, lineBreak: false });
        doc.y = shY + 42;

        // Summary
        if (sec.summary) {
          doc.font("Helvetica-Oblique").fontSize(10.5).fillColor(C.mid).text(sec.summary, M, doc.y, { width: CW, lineBreak: true });
          doc.y += 10;
        }

        // ── Key Concepts ────────────────────────────────────────────────────
        if (Array.isArray(sec.keyConcepts) && sec.keyConcepts.length > 0) {
          if (needsPage(50)) safeAddPage();
          doc.font("Helvetica-Bold").fontSize(9).fillColor(C.brand).text("KEY CONCEPTS", M, doc.y);
          doc.y += 6;
          // Render as pill-like inline tags
          const pillH = 18; const pillGap = 6;
          let px = M;
          sec.keyConcepts.forEach(concept => {
            const w = Math.min(doc.font("Helvetica").fontSize(9).widthOfString(concept) + 20, CW);
            if (px + w > PW - M) { px = M; doc.y += pillH + pillGap; }
            if (needsPage(pillH + pillGap)) { safeAddPage(); px = M; }
            doc.roundedRect(px, doc.y, w, pillH, 3).fillAndStroke(C.bg, C.divider);
            doc.font("Helvetica").fontSize(8.5).fillColor(C.mid).text(concept, px + 10, doc.y + 4, { lineBreak: false });
            px += w + pillGap;
          });
          doc.y += pillH + 14;
        }

        // ── Definitions ─────────────────────────────────────────────────────
        if (Array.isArray(sec.definitions) && sec.definitions.length > 0) {
          if (needsPage(60)) safeAddPage();
          doc.font("Helvetica-Bold").fontSize(9).fillColor(C.brand).text("DEFINITIONS", M, doc.y);
          doc.y += 8;
          sec.definitions.forEach(def => {
            if (needsPage(36)) safeAddPage();
            doc.font("Helvetica-Bold").fontSize(10).fillColor(C.dark).text(def.term + ":", M, doc.y, { lineBreak: false });
            doc.y += 14;
            doc.font("Helvetica").fontSize(10).fillColor(C.mid).text(def.definition, M + 16, doc.y, { width: CW - 16, lineBreak: true });
            doc.y += 10;
          });
          doc.y += 4;
        }

        // ── Formulas ────────────────────────────────────────────────────────
        if (Array.isArray(sec.formulas) && sec.formulas.length > 0) {
          if (needsPage(50)) safeAddPage();
          doc.font("Helvetica-Bold").fontSize(9).fillColor(C.brand).text("FORMULAS", M, doc.y);
          doc.y += 8;
          sec.formulas.forEach(formula => {
            if (needsPage(28)) safeAddPage();
            const fY = doc.y;
            doc.rect(M, fY, CW, 22).fill(C.bg);
            doc.font("Helvetica-Bold").fontSize(10.5).fillColor(C.dark).text(formula, M + 12, fY + 5, { width: CW - 20, lineBreak: false, ellipsis: true });
            doc.y = fY + 28;
          });
          doc.y += 4;
        }

        // ── Key Takeaways ────────────────────────────────────────────────────
        if (Array.isArray(sec.keyTakeaways) && sec.keyTakeaways.length > 0) {
          if (needsPage(50)) safeAddPage();
          doc.font("Helvetica-Bold").fontSize(9).fillColor(C.brand).text("KEY TAKEAWAYS", M, doc.y);
          doc.y += 8;
          sec.keyTakeaways.forEach(tk => {
            if (needsPage(22)) safeAddPage();
            doc.rect(M + 2, doc.y + 5, 5, 5).fill(C.brand);
            doc.font("Helvetica").fontSize(10).fillColor(C.mid).text(tk, M + 16, doc.y, { width: CW - 16, lineBreak: true });
            doc.y += 6;
          });
          doc.y += 4;
        }

        // Section divider
        doc.y += 8;
        doc.moveTo(M, doc.y).lineTo(PW - M, doc.y).strokeColor(C.divider).lineWidth(0.5).stroke();
        doc.y += 20;
      });

      // ── Quick Revision ────────────────────────────────────────────────────
      if (quickRevision.length > 0) {
        safeAddPage();
        const qrY = doc.y;
        doc.rect(M, qrY, CW, 32).fill(C.brand);
        doc.font("Helvetica-Bold").fontSize(14).fillColor(C.white).text("Quick Revision", M + 16, qrY + 8, { lineBreak: false });
        doc.y = qrY + 44;

        quickRevision.forEach((item, qi) => {
          if (needsPage(26)) safeAddPage();
          const rowY = doc.y;
          const isEven = qi % 2 === 0;
          doc.rect(M, rowY, CW, 24).fill(isEven ? C.bg : C.white);
          doc.font("Helvetica-Bold").fontSize(8.5).fillColor(C.brand).text(`${qi + 1}.`, M + 10, rowY + 7, { lineBreak: false });
          doc.font("Helvetica").fontSize(9.5).fillColor(C.dark).text(item, M + 28, rowY + 6, { width: CW - 34, lineBreak: false, ellipsis: true });
          doc.y = rowY + 26;
        });
      }

      // ── Post-process headers/footers ──────────────────────────────────────
      const range = doc.bufferedPageRange();
      const contentCount = range.count - 1;
      for (let pi = 1; pi < range.count; pi++) {
        doc.switchToPage(pi);
        _drawHeader(doc, title, pi);
        _drawFooter(doc, pi, contentCount, dateShort);
      }

      doc.flushPages();
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

// ─── Notes DOCX Builder ───────────────────────────────────────────────────────

async function buildNotesDOCX(notes) {
  const title    = notes.title   || "Study Notes";
  const subject  = notes.subject || "";
  const sections = Array.isArray(notes.sections) ? notes.sections : [];
  const quickRevision = Array.isArray(notes.quickRevision) ? notes.quickRevision : [];
  const dateLong = formatDateLong();

  const children = [];

  // Cover header
  children.push(new Paragraph({ children: [new TextRun({ text: "QUIZELO", bold: true, size: 56, color: "4f46e5" })], alignment: AlignmentType.CENTER, spacing: { after: 80 } }));
  children.push(new Paragraph({ children: [new TextRun({ text: "AI Study Notes Generator", size: 22, color: "94a3b8" })], alignment: AlignmentType.CENTER, spacing: { after: 300 } }));
  children.push(new Paragraph({ text: title, heading: HeadingLevel.HEADING_1, spacing: { after: 100 } }));
  if (subject) children.push(new Paragraph({ children: [new TextRun({ text: `Subject: ${subject}`, color: "475569", size: 22 })], spacing: { after: 80 } }));
  children.push(new Paragraph({ children: [new TextRun({ text: `Generated: ${dateLong}  |  ${sections.length} sections`, color: "94a3b8", size: 20 })], spacing: { after: 400 } }));
  children.push(new Paragraph({ border: { bottom: { color: "4f46e5", space: 1, value: BorderStyle.SINGLE, size: 12 } }, spacing: { after: 400 } }));

  sections.forEach((sec, si) => {
    children.push(new Paragraph({ text: sec.chapter || `Section ${si + 1}`, heading: HeadingLevel.HEADING_2, spacing: { before: 400, after: 160 } }));

    if (sec.summary) {
      children.push(new Paragraph({ children: [new TextRun({ text: sec.summary, italics: true, size: 22, color: "475569" })], spacing: { after: 200 } }));
    }

    if (Array.isArray(sec.keyConcepts) && sec.keyConcepts.length > 0) {
      children.push(new Paragraph({ children: [new TextRun({ text: "Key Concepts", bold: true, size: 22, color: "4f46e5" })], spacing: { before: 160, after: 80 } }));
      children.push(new Paragraph({ children: [new TextRun({ text: sec.keyConcepts.join("  ·  "), size: 20, color: "475569" })], spacing: { after: 160 } }));
    }

    if (Array.isArray(sec.definitions) && sec.definitions.length > 0) {
      children.push(new Paragraph({ children: [new TextRun({ text: "Definitions", bold: true, size: 22, color: "4f46e5" })], spacing: { before: 160, after: 80 } }));
      sec.definitions.forEach(def => {
        children.push(new Paragraph({ children: [new TextRun({ text: `${def.term}:  `, bold: true, size: 22 }), new TextRun({ text: def.definition, size: 20, color: "475569" })], spacing: { after: 80 }, indent: { left: 360 } }));
      });
    }

    if (Array.isArray(sec.formulas) && sec.formulas.length > 0) {
      children.push(new Paragraph({ children: [new TextRun({ text: "Formulas", bold: true, size: 22, color: "4f46e5" })], spacing: { before: 160, after: 80 } }));
      sec.formulas.forEach(f => {
        children.push(new Paragraph({ children: [new TextRun({ text: f, bold: true, size: 22, color: "1e293b" })], spacing: { after: 80 }, indent: { left: 360 } }));
      });
    }

    if (Array.isArray(sec.keyTakeaways) && sec.keyTakeaways.length > 0) {
      children.push(new Paragraph({ children: [new TextRun({ text: "Key Takeaways", bold: true, size: 22, color: "4f46e5" })], spacing: { before: 160, after: 80 } }));
      sec.keyTakeaways.forEach(tk => {
        children.push(new Paragraph({ children: [new TextRun({ text: `• ${tk}`, size: 20, color: "1e293b" })], spacing: { after: 80 }, indent: { left: 360 } }));
      });
    }

    children.push(new Paragraph({ border: { bottom: { color: "e2e8f0", space: 1, value: BorderStyle.SINGLE, size: 6 } }, spacing: { after: 200 } }));
  });

  if (quickRevision.length > 0) {
    children.push(new Paragraph({ text: "Quick Revision", heading: HeadingLevel.HEADING_1, pageBreakBefore: true, spacing: { before: 200, after: 300 } }));
    quickRevision.forEach((item, qi) => {
      children.push(new Paragraph({ children: [new TextRun({ text: `${qi + 1}.  `, bold: true, size: 22 }), new TextRun({ text: item, size: 22, color: "1e293b" })], spacing: { after: 100 } }));
    });
  }

  const docx = new Document({ creator: "Quizelo", title, sections: [{ properties: {}, children }] });
  return Packer.toBuffer(docx);
}

